### ISSUE TITLE
Selectings databases

### ISSUE THREAD

**Issue by GuiltyNL** [cdemi/PRTG-Redis-Sensor#11]
I've installed your Redis Sensor today, much appreciated! 

But it seems that you don't have the possibility to add other databases that database 0? We are using Redis with our Magento solution and in our case 3 databases are used (0,1,2) I really would love to have the other databases in PRTG too. Would this be possible?
  
Oh, shoot. I just noticed that pull request. ;)

**Comment by cdemi** [comment]
Lately I am a little bit busy :(

But as you noticed there is Pull Request #10 that aims to fix this. Hopefully I will try to find some time to fix this or maybe I'll try to ping @LegendOfGIT :)

**Comment by GuiltyNL** [comment]
Don't worry, take your time. Thanks for the fast reply
