### ISSUE TITLE
Connection to Azure redis cache with key

### ISSUE THREAD

**Issue by olsonnn** [cdemi/PRTG-Redis-Sensor#13]
is it possible?

Azure redis cache requires a key to connect.

**Comment by micdenny** [comment]
what do you mean with a key? a password?

**Comment by olsonnn** [comment]
yes, so when i do this: it can't connect:
stgflvrscbda001.redis.cache.windows.net:6379 <key>

i was trying to do some debugging with the exe it self but iget this then:
(not sure what i need to do to run the exe manually from cmd)

"PRTG Redis Sensor.exe" stgflvrscbda001.redis.cache.windows.net:6379 <key>

Unhandled Exception: StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketFailure on PING
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Func`1 multiplexerFactory, TextWriter log)
   at StackExchange.Redis.ConnectionMultiplexer.Connect(String configuration, TextWriter log)
   at PRTG_Redis_Sensor.Program.Main(String[] args)

**Comment by cdemi** [comment]
You need to make sure that the Azure Firewall allows connections from your PRTG Server. Can you establish a connection from your PRTG server to Azure Redis? You can even test with Telnet if you want

**Comment by olsonnn** [comment]
Test-NetConnection <myserver>.redis.cache.windows.net-port 6379
TcpTestSucceeded : True

so yes, i can reach it...

**Comment by olsonnn** [comment]
https://blog.cdemi.io/monitoring-redis-in-prtg/#fn1
the only thing i noticed here is that the zip file should contain 3 files. The exe and???
My downloaded zip has only the exe. Am i missing something?
