### ISSUE TITLE
Issue while installing

### ISSUE THREAD

**Issue by kakaday22** [cdemi/PRTG-Redis-Sensor#16]
When running the installer I am getting an argumentNullException when using password that contains "$"  I am using the installer as told "file.exe" <host:port> <password>

**Comment by cdemi** [comment]
Hi, I cannot reproduce this issue. I am able to connect to my test redis server using `127.0.0.1:6378 pass$test` as parameters

**Comment by cdemi** [comment]
Can you try passing your parameters as `127.0.0.1:6378 "pass$test"`? Otherwise, can you please give me more details of how you are using this?

**Comment by kakaday22** [comment]
I tried that and now I am getting the following error:
`StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketFailure on PING`

**Comment by cdemi** [comment]
Can you connect to the Redis server using that password with another client?

**Comment by kakaday22** [comment]
yes, I use Redis Desktop Manager and works to connect just fine  I am also able to connect via redis-cli
