### ISSUE TITLE
Upgrade to a self-contained .NET Core Single File application

### ISSUE THREAD

**Issue by cdemi** [cdemi/PRTG-Redis-Sensor#17]

**Comment by micdenny** [comment]
try also with `-p:PublishTrimmed=true` to reduce the size on disk

**Comment by cdemi** [comment]
Thanks! Didn't know about this

**Comment by micdenny** [comment]
with simple project it should not create any issue, if you don't use dynamic or heavy reflection it should be safe to use it.
