### ISSUE TITLE
JSON: The returned JSON does not match the expected structure ('0.34' is not a valid integer value). (code: PE231)

### ISSUE THREAD

**Issue by szempy** [cdemi/PRTG-Redis-Sensor#19]
Hello i am getting this error:
XML: The returned XML does not match the expected schema. (code: PE233) -- JSON: The returned JSON does not match the expected structure ('0.34' is not a valid integer value). (code: PE231)

I am using the latest stable PRTG monitor: 21.1.66.1623
And the Sensor version also latest: 2.1.4
Redis version: 3.2.12

I suppose the problem is coming from this part of the json response:

 {
        "channel": "Instantaneous Input kbps",
        "value": "0.27",
        "unit": "BytesBandwidth"
      },
      {
        "channel": "Instantaneous Output kbps",
        "value": "1.58",
        "unit": "BytesBandwidth"
      },

**Comment by cdemi** [comment]
Thanks for reporting. I'm having a look

**Comment by cdemi** [comment]
Can you test with [sensor version 2.1.5](https://github.com/cdemi/PRTG-Redis-Sensor/releases/tag/2.1.5) please?

**Comment by szempy** [comment]
Thank you very much.
Adding Float solved the problem.

**Comment by cdemi** [comment]
You're welcome :) and thanks for reporting the issue
