### ISSUE TITLE
JSON: The returned JSON does not match the expected structure ('0,01' is not a valid integer value). (code: PE231)

### ISSUE THREAD

**Issue by calon85** [cdemi/PRTG-Redis-Sensor#21]
Hello i am getting this error:

XML: The returned XML does not match the expected schema. (code: PE233) -- JSON: The returned JSON does not match the expected structure ('0,016' is not a valid integer value). (code: PE231)

I am using the latest stable PRTG monitor: 21.2.67.1562
And the Sensor version also latest: 2.1.6

I suppose the problem are:
 - Italy regional setting (in this case the "decimal separetor is ",")
-  The response to json:
{
        "channel": "Hit Rate",
        "value": "0,016042780748663103",
        "unit": "Percent",
        "Float": 1
      }

**Comment by cdemi** [comment]
Can you see if this one works correctly: https://github.com/cdemi/PRTG-Redis-Sensor/suites/2733229983/artifacts/60340958

**Comment by calon85** [comment]
Hi, It works

**Comment by cdemi** [comment]
Perfect I have merged the change to the normal release
