### ISSUE TITLE
Sensor failing due to divide by zero when calculating Hit Rate

### ISSUE THREAD

**Issue by erikruggles** [cdemi/PRTG-Redis-Sensor#25]
We are running into an issue in our lab environment where some of our slaves are receiving no traffic. This causes the Hit Rate calculation perform divide by zero chsarp converts into NaN when calling .ToString() on the result as keyspace_hits and keyspace_misses are both zero.

I propose that a SafeGetFloat method be used much like SafeGetInt32 which returns 0 if there is an error or if the result of the operation is NaN.

**Comment by erikruggles** [comment]
I created pull request #26 to address this.

**Comment by cdemi** [comment]
Thanks for contributing! If the build passes I will merge it :)

**Comment by cdemi** [comment]
PR #26 merged. Thanks!
