### ISSUE TITLE
XML: The returned XML does not match the expected schema. (code: PE233) -- JSON: The returned JSON does not match the expected structure (Invalid JSON.). (code: PE231)

### ISSUE THREAD

**Issue by jay1891** [cdemi/PRTG-Redis-Sensor#31]
Hi,

Thank you for this nice sensor. Sadly it is not working and PRTG is showing the following error all the time.

XML: The returned XML does not match the expected schema. (code: PE233) -- JSON: The returned JSON does not match the expected structure (Invalid JSON.). (code: PE231)

What could be the reason for this?

In the repo readme file you mention: "Set the parameters to pass to the executable (see the samples)"
Where are the samples?

**Comment by cdemi** [comment]
Could you send a screenshot of the PRTG setup for the sensor please? In the parameters section you need to pass the ServerIPorHostname:Port and the Redis Password if you have

**Comment by jay1891** [comment]
Hi,

The following parameters are set.

![image](https://user-images.githubusercontent.com/14939333/145196344-49dd815a-49e2-4870-b296-eb4b9ed5d3e1.png)

**Comment by cdemi** [comment]
If you manually run the exe with the parameters you set what is the response you get?

``` "PRTG.Redis.Sensor.exe" <ServerIPorHostname:Port> <Password?> ```

**Comment by jay1891** [comment]
An exception occurs that the Source parameter can not be null.

![image](https://user-images.githubusercontent.com/14939333/145198015-871b3cc1-6743-44f7-9357-3039cd7cae00.png)

**Comment by cdemi** [comment]
Hmm yes it looks like there's a bug in this sensor for Redis on Azure. I will take a look at it and get back to you

**Comment by jay1891** [comment]
Hi, 

I created a pull request that solved multiple json issues, if you allow it?

There were not only the "value cannot be null" exception related to null IGrouping objects, but also missing value fields in the json result. Essentially the changes that are made are for:
- checking if e.g. serverInfo, clientsinfo... an other grouping containers are not null, if they are null a default value is given.
- because sometimes there is no value, the json value field is not generated by the parser. But PRTG complainted that it needs value fields.
- Soms little property renaming to be more conform C# styling

At the moment it works ok for me. I think I didn't change anything fundamental. Maybe some little check by you could validate that.(?)

**Comment by cdemi** [comment]
Thanks a lot for the contribution! I have been quite busy lately and I really appreciate community contribution.

**Comment by jay1891** [comment]
After multiple adjustments I just notice that the current solution has now double null checking for almost each field and a few times it should still be added (e.g. at the end). So possibly it can be simplified and improved some more. I will try to improve this some more in the future.

Thank you for starting this nice solution!
