### ISSUE TITLE
The returned JSON does not match the expected structure

### ISSUE THREAD

**Issue by martinohansen** [cdemi/PRTG-Redis-Sensor#6]
Hi, first of all thanks alot for this custom prtg sensor, we have been really happy with it.

But all of the sudden our sensors is throwing us this error,
`
XML: The returned XML does not match the expected schema. (code: PE233) -- JSON: The returned JSON does not match the expected structure (Invalid JSON.). (code: PE231)
`

We are running PRTG Network Monitor 17.3.33.2830 and the latest release from this repository. 

Hope you can help, thanks.

**Comment by micdenny** [comment]
@martinohansen sorry about that.

The version v1.0 I've tested in production and it works, but I didn't have chance to test v1.1

Are you having problem with the v1.1?

Can you also try the v1.0?

**Comment by martinohansen** [comment]
That works, thanks.

**Comment by micdenny** [comment]
> That works, thanks.

which one works? v1.0 / v1.1 or both?

**Comment by martinohansen** [comment]
I switched to v1.0 and it now works, v1.1 did not work.

**Comment by micdenny** [comment]
> I switched to v1.0 and it now works, v1.1 did not work.

does your redis have some keys or it's a new redis just started? because the only problem I see is that keyspace can be empty if there's no keys already and I should push a fix for that, but apart from that I don't see other problems.

**Comment by martinohansen** [comment]
Its old redis servers with a few mb of keys, used as a frontend for elasticstack. It might be my prtg server installation i can't deny that for sure.

**Comment by micdenny** [comment]
@martinohansen if you run on your redis instance this command what do you see?

`redis-cli info keyspace`

**Comment by micdenny** [comment]
> The redis server is actually empty most of the time, looks relevant to #7

ok thank you, I will push a fix today so you can try

**Comment by micdenny** [comment]
PR #8 submitted

**Comment by micdenny** [comment]
@martinohansen here we go: https://github.com/cdemi/PRTG-Redis-Sensor/releases/tag/v1.2

tell us if that version works also for you, then feel free to close this issue.

**Comment by martinohansen** [comment]
v1.2 works, thanks alot guys.

**Comment by NoahSDS** [comment]
I'm trying to set up the Redis sensor and I'm getting the same error. I've tried v1.2 and 20181205.6 and both give the same error when I try running from cmd or from prtg:

C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML>".\PRTG Redis Sensor.exe" 10.1.43.111:6379

Unhandled Exception: StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketFailure on PING
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Func`1 multiplexerFactory, TextWriter log)
   at StackExchange.Redis.ConnectionMultiplexer.Connect(String configuration, TextWriter log)
   at PRTG_Redis_Sensor.Program.Main(String[] args)

**Comment by cdemi** [comment]
Can you telnet to Redis port from PRTG Machine?
________________________________

**Comment by NoahSDS** [comment]
When I try to telnet to port 6379 my cmd seems to freeze up. Ctrl-C doesn’t kill it. I have to actually close the cmd window.

I should have mentioned before: we are on AWS using their ElastiCache Redis service and we are using ssl on the connection.

I’m new to redis so please forgive me if I’m missing something obvious.

Thank you.

**Comment by NoahSDS** [comment]
Ah, I think I figured it out. I installed stunnel on the remote probe server and I'm now able to connect using your sensor.

Thank you.

**Comment by cdemi** [comment]
Perfect! You’re welcome
