### ISSUE TITLE
Add evicted_keys to stats monitor

### ISSUE THREAD

**Issue by marcos-guerrero** [cdemi/PRTG-Redis-Sensor#60]
Hello!
First of all, thank you very much for this PRTG sensor, it's very useful!
I'm missing evited_keys in the stats monitor, if I'm right and the stats Monitor gathers data by issuing an INFO command to the redis server, you could add evicted_keys value to a new channel in the stats monitor
Thanks in advance for take it into consideration

**Comment by cdemi** [comment]
Hi, thanks for the kind words. I should have added `evicted_keys` but I haven't tested it since I no longer have a usable redis server, however I think it should work. Hopefully 3.0.25 works for you: https://github.com/cdemi/PRTG-Redis-Sensor/releases/tag/3.0.25

**Comment by marcos-guerrero** [comment]
Thank you very much for your ultra-fast release!!!!!!!
Now I have Evicted Keys on my PRTG

Thanks again!
