### ISSUE TITLE
Connect to Redis with username and password and got error >> XML: The returned XML does not match the expected schema. (code: PE233) -- JSON: The returned JSON does not match the expected structure (Invalid JSON.). (code: PE231)

### ISSUE THREAD

**Issue by KathySwe** [cdemi/PRTG-Redis-Sensor#80]
I am using Redis 6 version and it required both username and password to connect
So I modified the program and copy "PRTG Redis Sensor.exe" to "programfiles(x86)\PRTG Network Monitor\Custom Sensors\EXEXML".

In PRTG website, I am getting below error
"XML: The returned XML does not match the expected schema. (code: PE233) -- JSON: The returned JSON does not match the expected structure (Invalid JSON.). (code: PE231)"

In Sensor Log, I got below error
"The application to execute does not exist: 'C:\Program Files (x86)\PRTG Network Monitor\custom sensors\EXEXML\PRTG Redis Sensor.dll'."

My question is, Do I need to copy "PRTG Redis Sensor.dll" too?

**Comment by cdemi** [comment]
What do you get if you run `"PRTG.Redis.Sensor.exe" -t Stats -e myredis.domain.local:6379` from the directory where you have the EXE?
