### ISSUE TITLE
Passing password to sensor

### ISSUE THREAD

**Issue by kocane** [cdemi/PRTG-Redis-Sensor#9]
After adding a password on the redis server, the prtg sensor returns error:
` JSON: The returned JSON does not match the expected structure (Invalid JSON.). (code: PE231)`  

How do I pass the password to the sensor?

**Comment by martinohansen** [comment]
Hi, we are still having this issue. How can i enter the redis password to the sensor?

**Comment by micdenny** [comment]
I would like to advise you that using a password on redis is not a best practice to secure your instance, instead it should be hided in a private network:

> Redis is designed to be accessed by trusted clients inside trusted environments. This means that usually it is not a good idea to expose the Redis instance directly to the internet or, in general, to an environment where untrusted clients can directly access the Redis TCP port or UNIX socket.

> In general, Redis is not optimized for maximum security but for maximum performance and simplicity.

> Access to the Redis port should be denied to everybody but trusted clients in the network, so the servers running Redis should be directly accessible only by the computers implementing the application using Redis.

> While Redis does not try to implement Access Control, it provides a tiny layer of authentication that is optionally turned on editing the redis.conf file.

> The AUTH command, like every other Redis command, is sent unencrypted, so it does not protect against an attacker that has enough access to the network to perform eavesdropping.

> Redis does not support encryption.

source: https://redis.io/topics/security

**Told this, I would like to provide you a way to achieve this** 😄  hold on...

**Comment by micdenny** [comment]
@kocane @martinohansen this feature was already implemented just pass another argument to the exe:

`PRTG Redis Sensor.exe localhost:6379 password`
